name: Test Open Python file
on:
  push:
    # paths:
    #   - "src/posts/*.md"
    branches:
      - main

jobs:
  open-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Open Python file
        run: python src/python/json.py 006_test.md
